#!/usr/bin/env python3
"""
evaluate_batch.py

Local batch runner for the documentation quality evaluator.

Evaluates a set of documentation files — Markdown, MDX, and OpenAPI YAML —
in one run, prints an aligned score table, and optionally writes a Markdown
report. Unlike ci/evaluate_changed.py, it accepts files and folders anywhere
on disk, with no DOC_PATHS restriction and no git involvement.

Usage:
  python3 evaluate_batch.py samples/                      # every doc in a folder
  python3 evaluate_batch.py docs/ api/openapi.yaml        # mix folders and files
  python3 evaluate_batch.py samples/*.md -v               # shell globs work too
  python3 evaluate_batch.py docs/ --dry-run               # preview the file set
  python3 evaluate_batch.py . --exclude 'README.md'       # exclude by pattern
  python3 evaluate_batch.py docs/ --report batch_report.md
  python3 evaluate_batch.py docs/ --threshold 4

Behavior:
  * Folders are searched recursively for .md, .mdx, .yaml, and .yml files.
  * Folder recursion skips dependency and hidden directories (node_modules,
    .git, .github, and any other dot-directory) so a docs-repo run doesn't
    score hundreds of vendored READMEs and CI configs. Pass --all to disable
    the excludes. Explicitly named files are always evaluated.
  * YAML files must be OpenAPI/Swagger specs. Non-spec YAML found during
    folder recursion (linter rulesets, CI workflows) is skipped with a
    "not an OpenAPI spec" note; an explicitly named non-spec YAML is
    reported as an error.
  * Files with `skip-evaluation: true` frontmatter are skipped, as in CI.
  * Files matching --exclude patterns or a .docqualityignore entry are
    excluded. Use these for files whose frontmatter would be visible to
    readers — GitHub renders frontmatter in .md files as a table — and
    reserve the frontmatter flag for pages inside a docs site.
  * Files with no evaluable content after frontmatter and MDX stripping —
    e.g., spec-driven pages that are only frontmatter and component
    references — are skipped with a "no evaluable content" note instead of
    wasting an API call on a 400 error. They do not fail the gate.
  * --dry-run prints every file with its disposition (evaluate, skip, or
    error) and exits without opening the vector store or calling the API.
  * Exit code is 1 if any file scores below the threshold or errors, else 0,
    so the runner can gate scripts the same way the CI check gates PRs.

By default the console output shows the score table plus feedback for failing
docs only. -v/--verbose shows feedback for every doc; -q/--quiet shows just the
table. The Markdown report (--report) always contains the full feedback.

Prerequisites:
    1. Run build_index.py at least once to create the vector index.
    2. ANTHROPIC_API_KEY available in the environment (via .env locally).
"""

import argparse
import fnmatch
import os
import sys
from pathlib import Path

from evaluate_core import (
    classify_documents,
    evaluate_document,
    get_collection,
)
from report import overall_score, render_console, render_report

DOC_EXTS = (".md", ".mdx", ".yaml", ".yml")

# Directory names skipped during folder recursion (see _is_excluded). These
# hold vendored packages and tool configuration, not documentation under review.
EXCLUDED_DIRS = {"node_modules"}

# Optional per-folder exclusion list, read from each folder passed on the
# command line. See load_ignore_patterns.
IGNORE_FILE = ".docqualityignore"

FOOTER = ("_Generated by the doc-quality-evaluator batch runner "
          "(RAG-grounded, model: claude-haiku-4-5)._")


def load_ignore_patterns(folder: Path) -> list[str]:
    """
    Read exclusion patterns from a .docqualityignore file in `folder`.

    One glob pattern per line; blank lines and lines starting with `#` are
    ignored. Patterns are matched against the file's path relative to the
    folder, using forward slashes, and also against its bare filename so a
    pattern like `README.md` matches at any depth.

    Returns an empty list when the file does not exist.
    """
    ignore_path = folder / IGNORE_FILE
    if not ignore_path.is_file():
        return []
    patterns = []
    for line in ignore_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            patterns.append(line)
    return patterns


def matches_ignore(rel_path: str, patterns: list[str]) -> bool:
    """
    Return True if `rel_path` matches any glob pattern.

    Each pattern is tested against the full relative path and the bare
    filename, so both `agent/*.md` and `README.md` behave as expected. A
    pattern ending in `/` is treated as a directory prefix.
    """
    name = rel_path.rsplit("/", 1)[-1]
    for pat in patterns:
        if pat.endswith("/"):
            if rel_path.startswith(pat) or f"/{pat}" in f"/{rel_path}":
                return True
        elif fnmatch.fnmatch(rel_path, pat) or fnmatch.fnmatch(name, pat):
            return True
    return False


def _is_excluded(path: Path, root: Path) -> bool:
    """
    Return True if any directory between root and path is excluded from
    recursion: a dependency directory (EXCLUDED_DIRS) or a hidden
    dot-directory such as .git, .github, or .claude.
    """
    for part in path.relative_to(root).parts[:-1]:
        if part in EXCLUDED_DIRS or part.startswith("."):
            return True
    return False


def collect_docs(paths: list[str], include_all: bool = False,
                 exclude: list[str] | None = None):
    """
    Expand the given files and folders into a sorted, deduplicated list of
    evaluable documentation files. Folders are searched recursively, skipping
    dependency and hidden directories unless include_all is True. Explicitly
    named files are always included regardless of location.

    Exclusions come from two places, both external to the documents: the
    `exclude` glob patterns (from --exclude) and a .docqualityignore file in
    each folder searched. They apply to files found by recursion only — a file
    you name explicitly on the command line is always evaluated, since asking
    for a file by name is a clearer signal than a pattern written earlier.

    Returns (docs, discovered_yaml, excluded): the sorted file list, the subset
    of YAML paths found by recursion rather than named explicitly, and the
    sorted list of paths dropped by an exclusion rule. Discovered YAML that
    turns out not to be an OpenAPI spec is skipped during classification
    instead of erroring, since docs repos routinely contain configuration
    YAML; explicitly named YAML gets no such leniency.

    Raises FileNotFoundError for a path that does not exist, and ValueError
    for an explicitly named file with an unsupported extension — both are
    caller mistakes worth failing loudly on, rather than silently skipping.
    """
    docs: set[str] = set()
    explicit: set[str] = set()
    discovered_yaml: set[str] = set()
    excluded: set[str] = set()
    cli_patterns = list(exclude or [])

    for raw in paths:
        p = Path(raw)
        if p.is_dir():
            patterns = cli_patterns + load_ignore_patterns(p)
            for f in p.rglob("*"):
                if not (f.suffix in DOC_EXTS and f.is_file()):
                    continue
                if not include_all and _is_excluded(f, p):
                    continue
                rel = str(f.relative_to(p)).replace(os.sep, "/")
                if patterns and matches_ignore(rel, patterns):
                    excluded.add(str(f))
                    continue
                docs.add(str(f))
                if f.suffix in (".yaml", ".yml"):
                    discovered_yaml.add(str(f))
        elif p.is_file():
            if p.suffix not in DOC_EXTS:
                raise ValueError(
                    f"Unsupported file type: {raw} "
                    f"(supported: {', '.join(DOC_EXTS)})"
                )
            docs.add(str(p))
            explicit.add(str(p))
        else:
            raise FileNotFoundError(f"No such file or directory: {raw}")

    # An explicitly named file wins over any pattern that also matched it.
    excluded -= explicit
    return sorted(docs), discovered_yaml - explicit, sorted(excluded)


def _parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Batch-evaluate documentation files and gate on quality.")
    parser.add_argument("paths", nargs="+", metavar="PATH",
                        help="Files or folders to evaluate (folders are recursive).")
    parser.add_argument("--threshold", type=float,
                        default=float(os.environ.get("DOC_QUALITY_THRESHOLD", "3")),
                        help="Minimum passing overall score, 1-5 (default: %(default)g).")
    parser.add_argument("--report", metavar="FILE",
                        help="Also write a Markdown report to FILE.")
    parser.add_argument("--all", action="store_true",
                        help="Include dependency and hidden directories "
                             "(node_modules, .git, .github, and other "
                             "dot-directories) when searching folders.")
    parser.add_argument("--exclude", metavar="GLOB", action="append",
                        default=[],
                        help="Exclude files matching GLOB (repeatable). "
                             "Adds to any patterns in .docqualityignore.")
    parser.add_argument("--dry-run", action="store_true",
                        help="List the files that would be evaluated, with "
                             "their dispositions, then exit without calling "
                             "the API.")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-q", "--quiet", action="store_true",
                       help="Print the score table only (no feedback).")
    group.add_argument("-v", "--verbose", action="store_true",
                       help="Print feedback for every doc, not just failures.")
    return parser.parse_args(argv)


def main() -> int:
    args = _parse_args(sys.argv[1:])
    feedback_mode = "all" if args.verbose else "none" if args.quiet else "failures"

    try:
        docs, discovered_yaml, excluded = collect_docs(
            args.paths, include_all=args.all, exclude=args.exclude)
    except (FileNotFoundError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    to_evaluate, skipped, errors = classify_documents(docs, discovered_yaml)
    skipped += [(p, "excluded") for p in excluded]
    skipped.sort()

    if args.dry_run:
        for path in to_evaluate:
            print(f"evaluate  {path}")
        for path, reason in skipped:
            print(f"skip      {path}  ({reason})")
        for path, msg in errors:
            print(f"error     {path}  ({msg})")
        print(f"\nDry run: {len(to_evaluate)} file(s) would be evaluated, "
              f"{len(skipped)} skipped, {len(errors)} in error. "
              "No API calls were made.")
        return 0

    for path, reason in skipped:
        print(f"Skipping {path} ({reason})")

    if not to_evaluate and not errors:
        print("No documentation files require evaluation — nothing to score.")
        return 0

    try:
        collection = get_collection()
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    results: list[tuple[str, dict]] = []

    for path in to_evaluate:
        print(f"Evaluating {path} ...")
        try:
            result = evaluate_document(path, collection=collection)
            results.append((path, result))
        except Exception as exc:  # noqa: BLE001 — report any failure per-file
            print(f"  error: {exc}", file=sys.stderr)
            errors.append((path, str(exc).splitlines()[0]))

    print("\n" + render_console(results, errors, skipped,
                                threshold=args.threshold, feedback=feedback_mode))

    if args.report:
        report = render_report(results, errors, skipped,
                               threshold=args.threshold, footer=FOOTER)
        Path(args.report).write_text(report, encoding="utf-8")
        print(f"\nMarkdown report written to {args.report}")

    below = [p for p, r in results
             if (overall_score(r) is None) or (overall_score(r) < args.threshold)]
    failed = bool(below or errors)

    if failed:
        # One file per line: a comma-joined list of full paths is unreadable,
        # and this is the block the reader acts on.
        print(f"\nQuality gate FAILED (threshold {args.threshold:g}):",
              file=sys.stderr)
        for path in below:
            print(f"  {path}  (below threshold)", file=sys.stderr)
        for path, _msg in errors:
            print(f"  {path}  (error)", file=sys.stderr)
        return 1

    print(f"\nQuality gate PASSED (threshold {args.threshold:g}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
