"""
report.py

Shared report rendering for the documentation quality evaluator.

Two front ends drive the evaluator over multiple files and need the same
output in two forms:

  * ci/evaluate_changed.py — the GitHub Actions runner (Markdown report posted
    as a PR comment, plus a console table for the CI log)
  * evaluate_batch.py — the local batch runner (console table, plus an optional
    Markdown report file)

This module holds both renderers so the two runners can't drift apart.
Importing it has no side effects; every function is pure.

All functions take `results` as a list of (path, result) tuples, where each
result is the nested dict returned by evaluate_core.evaluate_document(), and
`errors` as a list of (path, message) tuples for files that could not be
evaluated.
"""

from evaluate_core import CRITERIA

# Marker comment used to find and update the sticky PR comment.
MARKER = "<!-- doc-quality-report -->"

DEFAULT_THRESHOLD = 3.0

_ABBR = {"clarity": "Clr", "completeness": "Cmp", "accuracy": "Acc",
         "consistency": "Con", "structure": "Str"}


# ── Result access helpers ────────────────────────────────────────────────────

def overall_score(result: dict):
    """Return the overall score as a float, or None if missing/malformed."""
    try:
        return float(result["overall"]["score"])
    except (KeyError, TypeError, ValueError):
        return None


def is_fail(result: dict, threshold: float = DEFAULT_THRESHOLD) -> bool:
    """A doc fails the gate when its overall score is missing or below threshold."""
    ov = overall_score(result)
    return ov is None or ov < threshold


def _fmt(score) -> str:
    """Format a score for display, tolerating strings, None, and missing values."""
    if isinstance(score, bool):  # guard: bool is a subclass of int
        return str(score)
    if isinstance(score, (int, float)):
        return f"{score:g}"
    return str(score) if score not in (None, "") else "?"


def _criterion(result: dict, name: str):
    """
    Return (score, feedback) for a criterion, tolerating malformed model output.

    The tool schema asks for each criterion as a {score, feedback} object, but the
    model can occasionally return a bare string or number instead. This never
    raises: a non-dict entry yields no score and its text as feedback.
    """
    entry = result.get(name) if isinstance(result, dict) else None
    if isinstance(entry, dict):
        return entry.get("score"), str(entry.get("feedback", "") or "").strip()
    if entry is None:
        return None, ""
    return None, str(entry).strip()


def _overall_summary(result: dict) -> str:
    entry = result.get("overall") if isinstance(result, dict) else None
    if isinstance(entry, dict):
        return str(entry.get("summary", "") or "").strip()
    return str(entry or "").strip()


def _norm_skipped(skipped) -> list[tuple[str, str]]:
    """
    Normalize skipped entries to (path, reason) tuples.

    Callers may pass bare path strings (reason defaults to "skip-evaluation",
    the only reason that existed before content-based skipping) or tuples.
    """
    out = []
    for entry in skipped or []:
        if isinstance(entry, str):
            out.append((entry, "skip-evaluation"))
        else:
            out.append((entry[0], entry[1]))
    return out


def _skipped_lines(skipped: list[tuple[str, str]]) -> list[str]:
    """
    Render the skipped files as a bulleted list, one file per line.

    A comma-joined paragraph becomes unreadable once more than a handful of
    files are skipped, and full paths make it worse — so this mirrors the
    console output's one-file-per-line layout.
    """
    lines = ["### Skipped files", ""]
    lines += [f"- `{p}` ({r})" for p, r in skipped]
    return lines


# ── Markdown report ──────────────────────────────────────────────────────────

def render_report(
    results: list[tuple[str, dict]],
    errors: list[tuple[str, str]],
    skipped: list[str] | None = None,
    threshold: float = DEFAULT_THRESHOLD,
    file_noun: str = "documentation file(s)",
    footer: str = ("_Generated by the doc-quality-evaluator "
                   "(RAG-grounded, model: claude-haiku-4-5)._"),
) -> str:
    """
    Render the full Markdown report: summary table plus per-file feedback.

    `file_noun` lets callers describe the file set ("changed documentation
    file(s)" in CI); `footer` sets the attribution line. `skipped` entries may
    be bare paths or (path, reason) tuples (see _norm_skipped).
    """
    skipped = _norm_skipped(skipped)
    lines = [MARKER, "## Documentation quality report", ""]

    if not results and not errors:
        lines.append("No documentation files required evaluation.")
        if skipped:
            lines.append("")
            lines += _skipped_lines(skipped)
        return "\n".join(lines) + "\n"

    total = len(results) + len(errors)
    summary = (
        f"Evaluated {total} {file_noun} against the knowledge "
        f"base. Threshold: overall score ≥ **{threshold:g}**."
    )
    if skipped:
        summary += f" {len(skipped)} file(s) skipped."
    lines.append(summary)
    lines.append("")

    # Summary table.
    header = ["File", "Overall"] + [c.capitalize() for c in CRITERIA] + ["Status"]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")

    for path, result in results:
        overall = overall_score(result)
        cells = [f"`{path}`", f"{overall:g}/5" if overall is not None else "?"]
        for c in CRITERIA:
            score, _ = _criterion(result, c)
            cells.append(_fmt(score))
        status = "Pass" if overall is not None and overall >= threshold else "Fail"
        cells.append(f"**{status}**")
        lines.append("| " + " | ".join(cells) + " |")

    for path, _msg in errors:
        cells = [f"`{path}`", "—"] + ["—"] * len(CRITERIA) + ["**Error**"]
        lines.append("| " + " | ".join(cells) + " |")

    lines.append("")

    # Per-file feedback in collapsible sections.
    for path, result in results:
        overall = overall_score(result)
        lines.append(f"<details><summary><code>{path}</code> — feedback</summary>")
        lines.append("")
        for c in CRITERIA:
            score, feedback = _criterion(result, c)
            lines.append(f"- **{c.capitalize()} ({_fmt(score)}/5):** {feedback}")
        summary = _overall_summary(result)
        lines.append(f"- **Overall ({overall:g}/5):** {summary}"
                     if overall is not None else f"- **Overall:** {summary}")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    if errors:
        lines.append("### Files that could not be evaluated")
        lines.append("")
        for path, msg in errors:
            lines.append(f"- `{path}`: {msg}")
        lines.append("")

    if skipped:
        lines += _skipped_lines(skipped)
        lines.append("")

    lines.append("---")
    lines.append(footer)
    return "\n".join(lines) + "\n"


# ── Console table ────────────────────────────────────────────────────────────

def render_console(
    results: list[tuple[str, dict]],
    errors: list[tuple[str, str]],
    skipped: list[str] | None = None,
    threshold: float = DEFAULT_THRESHOLD,
    feedback: str = "failures",
) -> str:
    """Render an aligned, fixed-width table for terminal/CI-log readability.

    The Markdown report (render_report) is what gets posted or saved; this
    plainer version is only what prints to stdout, where Markdown pipes are
    hard to scan. Variable-width File column comes last so the numbers stay aligned.

    `feedback` controls the detail block under the table:
      "failures" (default) — feedback only for docs that fail the gate
      "all"                 — feedback for every doc
      "none"                — no feedback, table only

    `skipped` entries may be bare paths or (path, reason) tuples.
    """
    skipped = _norm_skipped(skipped)
    head = (f"{'Status':<6} {'Overall':>7}  "
            + "  ".join(f"{_ABBR[c]:>3}" for c in CRITERIA) + "  File")
    out = [f"Documentation quality — threshold: overall >= {threshold:g}", "",
           head, "-" * len(head)]

    def row(status: str, overall, scores, path: str) -> str:
        ov = f"{overall:g}".rjust(7) if isinstance(overall, (int, float)) else str(overall).rjust(7)
        cols = "  ".join(_fmt(s).rjust(3) for s in scores)
        return f"{status:<6} {ov}  {cols}  {path}"

    for path, result in results:
        ov = overall_score(result)
        status = "PASS" if ov is not None and ov >= threshold else "FAIL"
        scores = [_criterion(result, c)[0] for c in CRITERIA]
        out.append(row(status, ov if ov is not None else "?", scores, path))
    for path, _msg in errors:
        out.append(row("ERROR", "-", ["-"] * len(CRITERIA), path))
    for path, _reason in skipped:
        out.append(row("SKIP", "-", ["-"] * len(CRITERIA), path))

    # Per-file feedback under the table (controlled by `feedback`).
    if feedback != "none":
        shown = (results if feedback == "all"
                 else [(p, r) for p, r in results if is_fail(r, threshold)])
        if shown:
            heading = "Feedback" if feedback == "all" else "Feedback (failing docs)"
            out += ["", heading, "-" * len(heading)]
            for path, result in shown:
                ov = overall_score(result)
                status = "PASS" if ov is not None and ov >= threshold else "FAIL"
                ov_str = _fmt(ov) if ov is not None else "?"
                out += ["", f"{path}  ({status}, overall {ov_str}/5)"]
                for c in CRITERIA:
                    score, fb = _criterion(result, c)
                    out.append(f"  {c.capitalize()} ({_fmt(score)}/5): {fb}")
                summary = _overall_summary(result)
                if summary:
                    out.append(f"  Overall ({ov_str}/5): {summary}")

    if errors:
        out += ["", "Errors", "------"]
        for path, msg in errors:
            out.append(f"  {path}: {msg}")

    if skipped:
        out += ["", "Skipped", "-------"]
        for path, reason in skipped:
            out.append(f"  {path}  ({reason})")

    return "\n".join(out)
