#!/usr/bin/env python3
"""
ci/evaluate_changed.py

GitHub Actions runner for the documentation quality evaluator.

On a pull request it:
  1. Determines which documentation files changed (added/modified) versus the
     PR base branch.
  2. Scores each with evaluate_core.evaluate_document().
  3. Writes a Markdown report (ci_report.md) that the workflow posts as a
     sticky PR comment.
  4. Reports pass/fail via step outputs and a non-zero exit so the workflow can
     turn the check red when any doc scores below the threshold.

Configuration (environment variables):
  GITHUB_BASE_REF        PR base branch (set automatically by GitHub Actions).
                         When unset, the script runs locally against files
                         passed as arguments, or every doc under DOC_PATHS.
  DOC_PATHS              Directory holding the docs under evaluation.
                         Default: "samples".
  DOC_QUALITY_THRESHOLD  Minimum acceptable "overall" score (1–5). Default: 3.
  DOC_QUALITY_REPORT     Output path for the Markdown report.
                         Default: "ci_report.md".
  GITHUB_OUTPUT          Step-output file (set automatically by GitHub Actions).

Local usage:
  python3 ci/evaluate_changed.py                 # evaluate all docs under DOC_PATHS
  python3 ci/evaluate_changed.py samples/x.mdx   # evaluate specific files
  python3 ci/evaluate_changed.py -v              # include feedback for every doc
  python3 ci/evaluate_changed.py -q              # score table only, no feedback

By default the console output shows the score table plus feedback for failing
docs only. -v/--verbose shows feedback for all docs; -q/--quiet shows just the
table. These flags affect stdout only — the Markdown report (and the PR comment)
always contains the full per-criterion feedback.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

# Import the shared core from the repo root regardless of where this is invoked.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from evaluate_core import (  # noqa: E402
    classify_documents,
    evaluate_document,
    get_collection,
)
from report import overall_score, render_console, render_report  # noqa: E402

DOC_PATHS   = os.environ.get("DOC_PATHS", "samples")
THRESHOLD   = float(os.environ.get("DOC_QUALITY_THRESHOLD", "3"))
REPORT_PATH = os.environ.get("DOC_QUALITY_REPORT", "ci_report.md")
DOC_EXTS    = (".md", ".mdx", ".yaml", ".yml")

FOOTER = ("_Generated by the doc-quality-evaluator GitHub Action "
          "(RAG-grounded, model: claude-haiku-4-5)._")


# ── Determine which docs to evaluate ─────────────────────────────────────────

def _is_doc(path: str) -> bool:
    p = Path(path)
    return (
        p.suffix in DOC_EXTS
        and str(p).replace(os.sep, "/").startswith(f"{DOC_PATHS}/")
        and p.is_file()
    )


def changed_docs(explicit_files: list[str] | None = None) -> list[str]:
    """Return the doc files to evaluate for this run."""
    base = os.environ.get("GITHUB_BASE_REF")

    if base:
        # Pull request: diff HEAD against the base branch.
        subprocess.run(["git", "fetch", "origin", base], check=False,
                       capture_output=True)
        diff = subprocess.run(
            ["git", "diff", "--name-only", "--diff-filter=d",
             f"origin/{base}...HEAD"],
            capture_output=True, text=True, check=False,
        )
        candidates = diff.stdout.split()
    elif explicit_files:
        # Local run with explicit file arguments.
        candidates = explicit_files
    else:
        # Local run: evaluate everything under DOC_PATHS.
        candidates = [str(p) for p in Path(DOC_PATHS).rglob("*") if p.suffix in DOC_EXTS]

    return sorted({c for c in candidates if _is_doc(c)})


# ── Step outputs ─────────────────────────────────────────────────────────────

def set_output(name: str, value: str) -> None:
    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with open(out, "a", encoding="utf-8") as f:
            f.write(f"{name}={value}\n")


# ── Main ─────────────────────────────────────────────────────────────────────

def _parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Evaluate changed documentation and gate on quality.")
    parser.add_argument("files", nargs="*",
                        help="Specific docs to evaluate (local runs only).")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-q", "--quiet", action="store_true",
                       help="Print the score table only (no feedback).")
    group.add_argument("-v", "--verbose", action="store_true",
                       help="Print feedback for every doc, not just failures.")
    return parser.parse_args(argv)


def main() -> int:
    args = _parse_args(sys.argv[1:])
    feedback_mode = "all" if args.verbose else "none" if args.quiet else "failures"

    docs = changed_docs(args.files)
    # Every file here was discovered from a diff rather than named by a person,
    # so a YAML that turns out not to be an OpenAPI spec is skipped with a
    # reason instead of failing the check. This matches the batch runner.
    discovered_yaml = {d for d in docs if d.endswith((".yaml", ".yml"))}
    to_evaluate, skipped, errors = classify_documents(docs, discovered_yaml)

    for path, reason in skipped:
        print(f"Skipping {path} ({reason})")

    if not to_evaluate and not errors:
        report = render_report([], [], skipped, threshold=THRESHOLD,
                               file_noun="changed documentation file(s)",
                               footer=FOOTER)
        Path(REPORT_PATH).write_text(report, encoding="utf-8")
        print("No documentation files require evaluation — nothing to score.")
        set_output("changed", "false")
        set_output("result", "pass")
        return 0

    # Reuse one collection handle across all files.
    try:
        collection = get_collection()
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    results: list[tuple[str, dict]] = []

    for path in to_evaluate:
        print(f"Evaluating {path} ...")
        try:
            result = evaluate_document(path, collection=collection)
            results.append((path, result))
        except Exception as exc:  # noqa: BLE001 — report any failure per-file
            print(f"  error: {exc}", file=sys.stderr)
            errors.append((path, str(exc).splitlines()[0]))

    report = render_report(results, errors, skipped, threshold=THRESHOLD,
                           file_noun="changed documentation file(s)",
                           footer=FOOTER)
    Path(REPORT_PATH).write_text(report, encoding="utf-8")
    print("\n" + render_console(results, errors, skipped, threshold=THRESHOLD,
                                feedback=feedback_mode))

    # Gate: fail if any file scored below threshold or could not be evaluated.
    below = [p for p, r in results
             if (overall_score(r) is None) or (overall_score(r) < THRESHOLD)]
    failed = bool(below or errors)

    set_output("changed", "true")
    set_output("result", "fail" if failed else "pass")

    if failed:
        # One file per line — see the matching block in evaluate_batch.py.
        print(f"\nQuality gate FAILED (threshold {THRESHOLD:g}):", file=sys.stderr)
        for path in below:
            print(f"  {path}  (below threshold)", file=sys.stderr)
        for path, _msg in errors:
            print(f"  {path}  (error)", file=sys.stderr)
        return 1

    print(f"\nQuality gate PASSED (threshold {THRESHOLD:g}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
